apiVersion: v1
kind: Service
metadata:
  name: blog000ser
spec:
  type: NodePort
  ports:
  - port: 8099
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: blog000kube  