apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb  
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
             secretKeyRef:
               name: mariadb-secret # Secret의 이름
               key: password # Secret의 data에 들어간 key:value
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      volumes: # kubectl exec -it mariadb-56d685bcd-pnbwd -- bash (ID 생성 및 권한 주기)
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pv-claim