apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-volume
  labels:
    type: local
spec:
  storageClassName:  mariadb-storage-class
  capacity:
    storage: 20Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"